apiVersion: v1
kind: Service
metadata:
  name: quizroom-backend-service
spec:
  selector:
    app: quizroom-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
