apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizroom-frontend
  labels:
    app: quizroom-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quizroom-frontend
  template:
    metadata:
      labels:
        app: quizroom-frontend
    spec:
      containers:
        - name: quizroom-frontend
          image: badrinarayanan1/quizroom-frontend:latest
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              value: "http://quizroom-backend-service:3000"
