apiVersion: v1
kind: Service
metadata:
  name: quizroom-frontend-service
spec:
  selector:
    app: quizroom-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: LoadBalancer
